### ISSUE TITLE
Add vim integration

### ISSUE THREAD

**Issue by ruben2020** [ruben2020/codequery#1]
Add vim integration (vim plugin).

**Comment by devjoe** [comment]
Here comes the long-awaited [Vim plugin](https://github.com/devjoe/vim-codequery) !

 It is not yet released, but core functions of CodeQuery are workable (with bugs).

I believe that building editor add-ons based on CodeQuery are the fastest ways to promote and grow this helpful tool.

**Comment by ruben2020** [comment]
Thanks @devjoe !
I will link it to the codequery main page when you're ready.

**Comment by devjoe** [comment]
Dear @ruben2020:

My plugin [looks right](https://github.com/devjoe/vim-codequery) now. I will release it in September. By the way, I already put your CodeQuery logo in my readme file, is it OK?
  
I plan to add some features to `cqsearch`:  

* New option: [`-n`]
  
<pre>show number of results only</pre>
  
* New parameter: [`-p 14`]

<pre>
show the number of results for each query type
  
Output looks like:
Symbol 57
Call 39
Caller 28
Callee 8
Function-Def 1
Class-Def 0
Member 0
Parent 0
Child 0
</pre>  

Can I or my friends implement it? Is there anything we have to watch out for?

**Comment by ruben2020** [comment]
Yes, sure.  You can use the logo.
Let me check the rest of your comment,

**Comment by devjoe** [comment]
Hi @ruben2020,
  
Thanks for your logo. 
  
My plugin is almost ready.  I am asking my friends to help me to test it these days. I will release the plugin when I get enough confidence.
   
By the way, do you have a plan to release a newer version of CodeQuery such as v0.16.a recently? If you do so, it will be easy for MacOS users to install newer enough CodeQuery to try my plugin.  It will be helpful. 🙏
  

Finally, the following figures show two of the usages if `cqsearch` can support the features I want to implement:
  
![](https://dl.dropboxusercontent.com/u/7414946/github/menu_show_num.png)

![](https://dl.dropboxusercontent.com/u/7414946/github/hud.png)

**Comment by ruben2020** [comment]
Hi @devjoe
I'll release a new version very soon.
Thank you very much for your contribution.

**Comment by ruben2020** [comment]
Hi @devjoe 
Just released a new version 0.17.0
Already submitted to homebrew [here](https://github.com/Homebrew/homebrew-core/pull/5212)

**Comment by albfan** [comment]
Hi, terrific tool and plugin you both! 

I'm digging into code and I want to suggest some changes. I have forked both tool and plugin but would prefer to collaborate with your projects rather than diverge from them.

plugin:
- fallback to `:grep` if no Ack plugin is installed
- Allow to load external generated database
- Allow to search all symbols from empty buffer

tool:
- Allow multiple `-t` options

If you find some of these enhancements interesting I will open related issue on respective project.

**Comment by devjoe** [comment]
Hi @albfan 

Thanks for your suggestions. My quick responses  are here:

　
_(1) fallback to :grep if no Ack plugin is installed_

Obviously, this is a good idea. It didn't occur to me. 

　
_(2) Allow to load external generated database_

Currently, vim-codequery loads database files from `.git/codequery/$language.db` or `$cwd/$language.db`.
You can manually generate CodeQuery database files by `cqmakedb` command.
　  
_(3) Allow to search all symbols from empty buffer_

You can try `:setf python` to enable searching python symbols in the empty buffer.

　
Feel free to create these issues in vim-codequery project. I am sure that we should do **(1)** (welcome to send me PR !! 😉). And we can discuss (2) and (3) more.

**Comment by albfan** [comment]
Great @devjoe All seems to fix mostly my needs. I will provide PR if I evolve plugin at any time. Btw I'm maintainer of https://github.com/albfan/ag.vim

**Comment by ruben2020** [comment]
I'll take a look at your suggestion for multiple `-t` options

**Comment by albfan** [comment]
@ruben2020 My use case is I index pakages in separate files (for simple maintenance) usings this script

https://github.com/albfan/dotfiles/blob/master/ctags-package

so I have a `~/.config/tags/glibc.tags`, `~/.config/tags/gtk3.tags`, `~/.config/tags/gcc.tags` and I link them to projects on demand.
