### ISSUE TITLE
Add a Notepad++ plugin

### ISSUE THREAD

**Issue by ruben2020** [ruben2020/codequery#37]
Users of Notepad++ should be able to search directly from the editor.

**Comment by pidgeon777** [comment]
I'm also greatly interested in a Notepad++ codequery plugin!

**Comment by pidgeon777** [comment]
Is it still possible?

**Comment by ruben2020** [comment]
Hi @pidgeon777 . Yes, it's always possible. Just not implemented yet. I take it you're requesting this feature and would find it very useful.

**Comment by pidgeon777** [comment]
Yes, in my opinion, you would bring together the best of two worlds (Notepad++, widely used by millions of users, and Notepad++).

Later today I'll try the CLI edition of CodeQuery in conjunction with the NppExec plugin of Notepad++.

Just more question, is the development of CodeQuey still ongoing?

**Comment by ruben2020** [comment]
The development of CodeQuery is still ongoing. Just that I'm a little busy, so updates may be slow. I think it's a great idea. I will give this plugin development a higher priority. In the mean time. You can search in CodeQuery GUI, but open the source file at the line you've selected in Notepad++.

**Comment by ruben2020** [comment]
Hi @pidgeon777 Would you prefer a plugin with Visual Studio Code or Notepad++ first? I am starting to work on a Visual Studio Code extension, because VS Code is usable on Windows, Linux and Mac, unlike Notepad++ which is only available for Windows.

**Comment by ruben2020** [comment]
This issue would be closed as it's unnecessary. There's already a vim plugin and a vscode plugin available, which are usable on Windows, Linux and Mac.
