### ISSUE TITLE
database file open error

### ISSUE THREAD

**Issue by Shashaankar** [ruben2020/codequery#38]
Hi Ruben,

I appreciate your work on this project, I basically rely heavily on ctags and cscope for code browsing. But when I tried to use your tool, it showed a pop-up saying 'file open error'. I followed steps written in documentation to generate the myproject.db file.

Here are some more information about the code I'm using.
1) All .c and .h files
2) Basically it's an embedded/firmware code base
3) The generated 'myproject.db' is almost 2.5 Giga bytes (hope you got sense of code base I'm using) - ofcourse it took about 45 mns to generate that file.
4) running on Ubuntu 12.04 

Let me know if you need more information, 
![image](https://cloud.githubusercontent.com/assets/4054482/2738918/e460631a-c69b-11e3-9ea9-e87d39a47b95.png)

**Comment by ruben2020** [comment]
Too old
