### ISSUE TITLE
I got "cqmakedb.exe has stopped working" popup in Windows 7

### ISSUE THREAD

**Issue by sgkimsm** [ruben2020/codequery#39]
Hello,

I started to use codequery and thank you for this open source tool.
But I have one problem with cqmakedb.exe.

I followed HOWTO-WINDOWS.txt but it stops working during processing ctags file.
# 

D:\Tmp\Source>cscope -cb
D:\Tmp\Source>ctags --fields=+i -n -R -L cscope.files
D:\Tmp\Source>cqmakedb -s .\my.db -c cscope.out -t tags -p
cscope.out sanity check OK
cscope.out detailed check OK
Adding symbols ...
Finalizing ...
Processing ctags file ...
-> here, I get "cqmakedb.exe has stopped working" error
# 

Although there is an error, it seems that I can use code search features, but I'm not sure it is complete or not.
So I'd like to know how I can help you to fix the error if you are available for this.

Thank you.

**Comment by ruben2020** [comment]
@sgkimsm 
This issue can be considered closed, thanks to @brianonn
