### ISSUE TITLE
codequery GUI tool should open DB files by command line argument

### ISSUE THREAD

**Issue by ruben2020** [ruben2020/codequery#4]
It should also support spaced file paths in Windows.

**Comment by brent-casavant-hpe** [comment]
Just stopping by to add an upvote for this.  I've used cscope for years and keep a cscope/ctags database per-branch of my git repository, and use a front-end script to select which database to use depending on which branch I currently have checked out.

I'm currently able to build a CodeQuery database in the same directory structure as I keep these per-branch cscope/ctags databases, but I'm unable to pass that database as an argument on the CodeQuery GUI command line.  As a workaround my front-end script is rewriting the CodeQuery.conf [OpenDBHistory] section before starting the GUI.  This works, but is a bit clunky.

**Comment by ruben2020** [comment]
@brent-casavant-hpe Thanks. This sounds like a worthwhile feature to add and it's easy I think.

**Comment by ruben2020** [comment]
@brent-casavant-hpe  I have added the ability to open CodeQuery database files by command line argument to the GUI. It's `codequery [path_to_CodeQuery_database_file_to_open]`. It's on the `develop` branch.

**Comment by ruben2020** [comment]
@brent-casavant-hpe Requested feature is now supported in v0.27.0.
