### ISSUE TITLE
double-free or corruption when building database

### ISSUE THREAD

**Issue by eapache** [ruben2020/codequery#42]
Given the following cscope and ctags databases (I gzipped them for sharing, so uncompress them first) to `cqmakedb` reliably causes a crash.
https://dl.dropboxusercontent.com/u/171647/codequery-samples/cscope.out.gz
https://dl.dropboxusercontent.com/u/171647/codequery-samples/tags.gz

The complete output:

```
➜  wireshark (master) cqmakedb -s ../cq.db -c cscope.out -t tags
cscope.out sanity check OK
cscope.out detailed check OK
Adding symbols ...
Finalizing ...
Processing ctags file ...
*** Error in `cqmakedb': double free or corruption (!prev): 0x00000000015cad60 ***
[1]    31449 abort (core dumped)  cqmakedb -s ../cq.db -c cscope.out -t tags
```

**Comment by ruben2020** [comment]
Bug fixed by @brianonn
