### ISSUE TITLE
Sanity Check Error is ambigious

### ISSUE THREAD

**Issue by ozzieg** [ruben2020/codequery#48]
I am getting a Sanity Check Error message (cscope.out sanity check Error) as soon as I run the command. I looked at the code and it looks like the actual Error Code is getting swallowed instead of being written out. It would be helpful to get the actual error code. I can also provide the cscope.out file for your perusal.

**Comment by ruben2020** [comment]
Sure. Please provide cscope.out. you can send it by email or attach it here. Thank you for your support.

**Comment by ozzieg** [comment]
You know what, I put "-q" and it worked. I suppose it didn't like not having the "-q". I will e-mail the file since I don't want it public.
