### ISSUE TITLE
cqmakedb gives cscope sanity check error

### ISSUE THREAD

**Issue by imtiazhussainsyed** [ruben2020/codequery#50]
Hi,
   I have created cscope.files and ctags as mentioned in 
http://ruben2020.github.io/codequery/windows-install/HOWTO-WINDOWS.txt
I still get this error. not sure what the problem is. any help would be appreciated. 
cscope -cb (BTW, this step just hangs). therefore, I run cscope once, which creates cscope,out automatically. 
ctags --fields=+i -n -R -L cscope.files
cqmakedb -s .\myproject.db -c cscope.out -t tags -p
cscope.out sanity check Error

I tried using just *.c files in cscope.files hoping to keep the code base smaller. But it doesn't seem to have helped.

**Comment by ruben2020** [comment]
Hi,
Is your code base open source? Can I get it and try it?

**Comment by imtiazhussainsyed** [comment]
No. Its not open source. However I will try with an open source package and will let you know.

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 13, 2016 at 7:27 pm, Ruben<notifications@github.com> wrote:   
Hi,
Is your code base open source? Can I get it and try it?

**Comment by VonFry** [comment]
@ruben2020 Hi, I have met the same problem.

My code is a test code which only has one class and a main function. I run cscope with `-b`.

```
#include <stdlib.h>
class test
{
public:
    test ();
    virtual ~test ();

private:
    
};

int main()
{
    return 0;
}
```

Cmd follow:

```
cscope -b
ctags -R --tag
cqmakedb -s ./myproject.db -c ./cscope.out -t ./tags -p
```

If I replace ctags cmd like:

`ctags --fields=+i -n -R -L ./cscope.files`

It has the same error.

`cscope.out sanity check Error`

My system is OS X 10.10. and install with brew.

And I try to use `-d` param, but it seems that nothing happened.

**Comment by ruben2020** [comment]
Yes. The `-c` will remove compression.

**Comment by gitofmine** [comment]
while tying to use codequery in my windows 7 as per the "How to steps" in w7
I get the following 

C:\codelite>ls
CMakeLists.txt   TestSpace        doc              showgraph
Doxyfile         cli              gui              tags
LICENSE.md       cmakefind        makedb           test
NEWS.txt         cscope.files     querylib         windows-install
README.md        cscope.out       release.json

C:\codelite>cscope -b         ( If I use -c option , I get errors.."cscope: -c or -T option mismatch between command line and old symbol database"  skipped -c to get it going)
C:\codelite>ctags --fields=+i -n -R -L cscope.files

C:\codelite>cqmakedb -s .\myproject.db -c cscope.out -t tags -p
cscope.out sanity check Error

Let me know , if  cscope.out  and files files are required.....

Can  some one help us out.

**Comment by gitofmine** [comment]
[files.zip](https://github.com/ruben2020/codequery/files/202262/files.zip)

**Comment by ruben2020** [comment]
I'll try it out

**Comment by ruben2020** [comment]
Hi @gitofmine 

The cscope.out in files.zip was not built with `-c`, and that's why it does not work. Why doesn't it work for you? Are using the latest version of cscope which is 15.8a?

Perhaps I should make the error description clearer for not using `-c`.

**Comment by ruben2020** [comment]
Now it will print warning for not using `-c`
