### ISSUE TITLE
License to GPL 2

### ISSUE THREAD

**Issue by sumonto** [ruben2020/codequery#55]
Hi,
Might be a mute question, but is there a way to make the license GPL v2, my company does not allow for GPL v3.

Thanks.

**Comment by ruben2020** [comment]
Hi @sumonto 
I can easily change the license to GPL v2 as I'm the owner, so there's no problem with that.
But does your company policy apply only to reuse of the code, or also for using the software?

**Comment by sumonto** [comment]
Thanks for the reply, it applies to both.

**Comment by ruben2020** [comment]
Actually GPLv3 doesn't offer any more benefits compared to GPLv2 for CodeQuery, and I can see some fierce opposition to GPLv3 from people like Linus Torvalds.

I need to replace one dependency (optlist from Michael Dipperstein) that uses LGPL v3. Then, I can change the license to GPL v2.

**Comment by ruben2020** [comment]
New version v0.18.0 released. Now already migrated to GPLv2. I made sure that there are no dependencies on GPLv3 or LGPLv3 any more.

**Comment by ruben2020** [comment]
I just discovered two problems.
- Qt5 is licensed under LGPLv3
- QScintilla2 (by Riverbank Computing) is licensed under GPLv3, which would automatically cause CodeQuery's GPLv2 license to be incompatible and forcing it to be upgraded to GPLv3.

I plan to change this by:
- Using another license for CodeQuery. I prefer Mozilla Public License 2.0 which is a file-based weak copyleft license.
- Replacing QScintilla2 with the original Scintilla (by Neil Hodgson) which is released under a free permissive license. Scintilla may have to be statically compiled with CodeQuery.

**Comment by ruben2020** [comment]
Now with the release of v0.19.0, the license has been changed to MPL v2.0 and QScintilla has been replaced with the original Scintilla.
Qt5.6 seems to be licensed under LGPL 2.1 and LGPL 3 but Qt5.8 is licensed under LGPL 3 only. But it's OK. Both are compatible with MPL v2.0.
