### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by cryptomaniac512** [ruben2020/codequery#56]
Hi! Can it support unicode?
![2017-02-16-144101_710x197_scrot](https://cloud.githubusercontent.com/assets/10251687/23007790/a32a90dc-f456-11e6-9eb1-502f02c900e1.png)

**Comment by ruben2020** [comment]
That's a good point. I've never tested it before.  I guess it's now a good time as any to add Unicode support. But I'm not sure about the different Unicode formats like plain Unicode, UTF-8, UTF-16 etc.

**Comment by cryptomaniac512** [comment]
Maybe set UTF-8 initially, but still allow users to set any other format? Or implement only UTF-8 support. I think UTF-8 is a good choice.

**Comment by ruben2020** [comment]
By default, it should be using the ISO-8859-1 (Latin 1) encoding, but I need to switch it to UTF-8 which should be easy. I will also decide if I need to make it a setting in the options menu to switch between UTF-8 and Latin 1. Based on historical trends, these are are two most popular encoding formats. From 2010 to 2016, the "market share" of UTF-8 has increased from 50.6% to 88.6%. ISO-8859-1 remains the second most popular choice.
https://w3techs.com/technologies/history_overview/character_encoding/ms/y

**Comment by ruben2020** [comment]
Hi @cryptomaniac512 I have added UTF-8 support. That should be sufficient. If you're building yourself, please use the latest of branch develop. I will release a new version soon. I've found that it is sufficient to support only UTF-8 in all cases. Thank you for your support and feedback.

**Comment by cryptomaniac512** [comment]
Works great! Thank you!
