### ISSUE TITLE
Cant compile on Linux: Could NOT find QScintilla (missing: QSCINTILLA_LIBRARY)

### ISSUE THREAD

**Issue by thegala** [ruben2020/codequery#59]
I am using latest upgraded Arch Linux. When trying to compile latest code from git  I get this error message
```
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find QScintilla (missing: QSCINTILLA_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmakefind/FindQScintilla.cmake:104 (find_package_handle_standard_args)
  gui/CMakeLists.txt:152 (FIND_PACKAGE)
```
Qscintilla is installed.

**Comment by ruben2020** [comment]
Hi @thegala 
There are two versions of qscintilla for Arch, one is based on Qt4 and the other based on Qt5. Please install both using:

`sudo pacman -S qscintilla-qt4 qscintilla-qt5`

I use the latest Arch Linux on my home laptop and I have no problems.

**Comment by thegala** [comment]
I think that I have both of them installed I fact I am pretty sure. Currently I have no access to computer so I can't check it .
I will give it try once I am back.

**Comment by ruben2020** [comment]
Sorry for the delay. I could reproduce the problem and I've fixed it, in the `develop` branch.

**Comment by ruben2020** [comment]
Now with CodeQuery v0.19.0, there is no more dependency on QScintilla.
