### ISSUE TITLE
How to install without gui

### ISSUE THREAD

**Issue by tenfyzhong** [ruben2020/codequery#62]
I use it with [vim-codequery](https://github.com/devjoe/vim-codequery) only. I no need gui. how can I install it without gui?

**Comment by johnzeng** [comment]
＋1

**Comment by ruben2020** [comment]
Hi @tenfyzhong @johnzeng 
I just added this feature, on your request.

Please get the latest commit from the master branch and build it using the following command:
`cmake -DNO_GUI=ON ..`

That is to say, follow the all the instructions in the INSTALL_LINUX.md file, but add `-DNO_GUI=ON` to the CMake options.

Please let me know if that meets your expectation and works for you. Thanks.

**Comment by ruben2020** [comment]
Added to INSTALL_LINUX.md
