### ISSUE TITLE
CodeQuery not finding Qt5 Libraries on Linux Mint 18.3 Cinnamon

### ISSUE THREAD

**Issue by alexbottoni** [ruben2020/codequery#69]
Error message when starting:

$ codequery
codequery: /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so.5: version `Qt_5' not found (required by codequery)
codequery: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by codequery)
codequery: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.8' not found (required by codequery)
codequery: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by codequery)
codequery: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by codequery)
codequery: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by codequery)

ldd is of little help:
$ ldd /usr/bin/codequery
/usr/bin/codequery: /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so.5: version `Qt_5' not found (required by /usr/bin/codequery)
/usr/bin/codequery: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by /usr/bin/codequery)
/usr/bin/codequery: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/bin/codequery)
/usr/bin/codequery: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /usr/bin/codequery)
/usr/bin/codequery: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /usr/bin/codequery)
/usr/bin/codequery: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by /usr/bin/codequery)
[cut]

Installed codequery package:
codequery-qt5-0.21.0-Linux-amd64.deb (codequery 0.21.10 for Linux 64 Bit & Qt 5)
(Taken from this website)
Accordingly with the DEB Installer (Synaptic), all dependencies are satisfied (even if QtCore 5.8 is listed amongst the dependencies of codequery and it is not present on my Qt 5.5.1 installation)

Platform:
Linux Mint 18.3 Cinnamon 64 Bit
Qt 5.5.1+dfsg-16ubuntu7.5 (coming from Ubuntu/Mint official repository, installed via Synaptic)

Synaptic list of installed Qt5 libraries:
libqt5clucene5/xenial-updates,now 5.5.1-3ubuntu0.1 amd64 [installed,automatic]
libqt5concurrent5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed,automatic]
libqt5core5a/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5dbus5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5designer5/xenial-updates,now 5.5.1-3ubuntu0.1 amd64 [installed,automatic]
libqt5designercomponents5/xenial-updates,now 5.5.1-3ubuntu0.1 amd64 [installed,automatic]
libqt5gui5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5help5/xenial-updates,now 5.5.1-3ubuntu0.1 amd64 [installed,automatic]
libqt5libqgtk2/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5network5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5opengl5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5printsupport5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5qml5/xenial,now 5.5.1-2ubuntu6 amd64 [installed]
libqt5quick5/xenial,now 5.5.1-2ubuntu6 amd64 [installed]
libqt5quickwidgets5/xenial,now 5.5.1-2ubuntu6 amd64 [installed,automatic]
libqt5script5/xenial,now 5.5.1+dfsg-2build1 amd64 [installed,automatic]
libqt5serialport5/xenial,now 5.5.1-2build1 amd64 [installed,automatic]
libqt5sql5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5sql5-sqlite/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5svg5/xenial,now 5.5.1-2build1 amd64 [installed]
libqt5test5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed,automatic]
libqt5webkit5/xenial,now 5.5.1+dfsg-2ubuntu1 amd64 [installed]
libqt5widgets5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]
libqt5x11extras5/xenial,now 5.5.1-3build1 amd64 [installed,automatic]
libqt5xml5/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]

Library files in path searched by Qt and codequery: 

/usr/lib/x86_64-linux-gnu $ ls | grep libQt5
libQt5CLucene.so.5
libQt5CLucene.so.5.5
libQt5CLucene.so.5.5.1
libQt5Concurrent.prl
libQt5Concurrent.so
libQt5Concurrent.so.5
libQt5Concurrent.so.5.5
libQt5Concurrent.so.5.5.1
libQt5Core.prl
libQt5Core.so
libQt5Core.so.5
libQt5Core.so.5.5
libQt5Core.so.5.5.1
libQt5DBus.prl
libQt5DBus.so
libQt5DBus.so.5
libQt5DBus.so.5.5
libQt5DBus.so.5.5.1
libQt5DesignerComponents.so.5
libQt5DesignerComponents.so.5.5
libQt5DesignerComponents.so.5.5.1
libQt5Designer.so.5
libQt5Designer.so.5.5
libQt5Designer.so.5.5.1
libQt5EglDeviceIntegration.prl
libQt5EglDeviceIntegration.so
libQt5EglDeviceIntegration.so.5
libQt5EglDeviceIntegration.so.5.5
libQt5EglDeviceIntegration.so.5.5.1
libQt5Gui.prl
libQt5Gui.so
libQt5Gui.so.5
libQt5Gui.so.5.5
libQt5Gui.so.5.5.1
libQt5Help.so.5
libQt5Help.so.5.5
libQt5Help.so.5.5.1
libQt5Network.prl
libQt5Network.so
libQt5Network.so.5
libQt5Network.so.5.5
libQt5Network.so.5.5.1
libQt5OpenGLExtensions.a
libQt5OpenGLExtensions.prl
libQt5OpenGL.so.5
libQt5OpenGL.so.5.5
libQt5OpenGL.so.5.5.1
libQt5PrintSupport.prl
libQt5PrintSupport.so
libQt5PrintSupport.so.5
libQt5PrintSupport.so.5.5
libQt5PrintSupport.so.5.5.1
libQt5Qml.so.5
libQt5Qml.so.5.5
libQt5Qml.so.5.5.1
libQt5Quick.so.5
libQt5Quick.so.5.5
libQt5Quick.so.5.5.1
libQt5QuickWidgets.so.5
libQt5QuickWidgets.so.5.5
libQt5QuickWidgets.so.5.5.1
libQt5Script.so.5
libQt5Script.so.5.5
libQt5Script.so.5.5.1
libQt5SerialPort.so.5
libQt5SerialPort.so.5.5
libQt5SerialPort.so.5.5.1
libQt5Sql.prl
libQt5Sql.so
libQt5Sql.so.5
libQt5Sql.so.5.5
libQt5Sql.so.5.5.1
libQt5Svg.so.5
libQt5Svg.so.5.5
libQt5Svg.so.5.5.1
libQt5Test.prl
libQt5Test.so
libQt5Test.so.5
libQt5Test.so.5.5
libQt5Test.so.5.5.1
libQt5WebKit.so.5
libQt5WebKit.so.5.5
libQt5WebKit.so.5.5.1
libQt5WebKitWidgets.so.5
libQt5WebKitWidgets.so.5.5
libQt5WebKitWidgets.so.5.5.1
libQt5Widgets.prl
libQt5Widgets.so
libQt5Widgets.so.5
libQt5Widgets.so.5.5
libQt5Widgets.so.5.5.1
libQt5X11Extras.so.5
libQt5X11Extras.so.5.5
libQt5X11Extras.so.5.5.1
libQt5XcbQpa.prl
libQt5XcbQpa.so
libQt5XcbQpa.so.5
libQt5XcbQpa.so.5.5
libQt5XcbQpa.so.5.5.1
libQt5Xml.prl
libQt5Xml.so
libQt5Xml.so.5
libQt5Xml.so.5.5
libQt5Xml.so.5.5.1

Found this clue:
https://stackoverflow.com/q/36128645/383821

But, it does not work anyway:
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu
$ echo $LD_LIBRARY_PATH
:/usr/lib/x86_64-linux-gnu
$ codequery
codequery: libQt5Concurrent.so.5: version `Qt_5' not found (required by codequery)
codequery: libQt5Xml.so.5: version `Qt_5' not found (required by codequery)
codequery: libQt5Core.so.5: version `Qt_5.8' not found (required by codequery)
codequery: libQt5Core.so.5: version `Qt_5' not found (required by codequery)
codequery: libQt5Gui.so.5: version `Qt_5' not found (required by codequery)
codequery: libQt5Widgets.so.5: version `Qt_5' not found (required by codequery)

Contact me if you need more info.

**Comment by ruben2020** [comment]
@alexbottoni I tested this with Linux 19.3 64-bit Cinnamon with the latest in CodeQuery's develop branch based on the latest instructions in the INSTALL-LINUX.md file, and it works fine now. The version of Qt tested against, was 5.9.5.

But stranglely, it sometimes crashes. This does not happen in Lubuntu 18.04 64-bit. I'm checking on that, but that's a different issue.
