### ISSUE TITLE
Dumb question regarding GUI

### ISSUE THREAD

**Issue by mvellon** [ruben2020/codequery#70]
If I'm viewing a function and double click on a call to another function, I see that the filename and line where the function is defined.  Is there any key or mouse gesture that will navigate to that file/line?

**Comment by ruben2020** [comment]
@mvellon At the moment, there isn't, but this is a good feature suggestion. I will look into it. Thanks.

**Comment by ruben2020** [comment]
@mvellon Unfortunately scintilla doesn't seem to have the ability to click annotations. But my original intention is that once you double-click and select a function name, you can click on the "copy, paste and search" button to search for it, then select from the result list.
