### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ruben2020/codequery#71]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [cs2sq](https://github.com/ruben2020/codequery/blob/46d9a7b1a7e86e024ed8af664f677c8b776cb304/makedb/cs2sq.cpp#L27 "Destructor for cs2sq")
- [csdbparser::destroy_buf](https://github.com/ruben2020/codequery/blob/f5645c59031504d7a9c7db3c5fcb89d77129831d/makedb/csdbparser.cpp#L235 "csdbparser::destroy_buf function")
- [tempbuf](https://github.com/ruben2020/codequery/blob/f5645c59031504d7a9c7db3c5fcb89d77129831d/querylib/small_lib.cpp#L252 "Destructor for tempbuf")

**Comment by ruben2020** [comment]
Fixed in the develop branch.
