### ISSUE TITLE
Why didn't the option to compile without GUI wasn't merged to v0.21.1?

### ISSUE THREAD

**Issue by doronbehar** [ruben2020/codequery#75]
As the title suggests, I've noticed The option to compile CodeQuery without GUI wasn't merged to `v0.21.1`. Here is the comparison link: https://github.com/ruben2020/codequery/compare/v0.21.1...master

Why?

**Comment by ruben2020** [comment]
Hi @doronbehar Now it has been merged into `v0.22.0`. Thank you for your support.
