### ISSUE TITLE
Any open API for batch operation to generate function called graphs instead of GUI?

### ISSUE THREAD

**Issue by FengWu1206** [ruben2020/codequery#77]
Is there any open API to generate function called graphs in the backend systems instead of GUI?

**Comment by ruben2020** [comment]
Currently there isn't. But this is quite easy to do, especially creating an output of Graphviz DOT files. I'll take this as a feature request.

**Comment by FengWu1206** [comment]
Thank you for response, any plan of a new version with auto-generate Graphviz DOT files? Your tools are very nice and I want to use it to do some research.

**Comment by ruben2020** [comment]
@FengWu1206 This has been added to the develop branch, and will be released soon.
