### ISSUE TITLE
Missing a QT5 library in Ubuntu 18.04

### ISSUE THREAD

**Issue by richliu** [ruben2020/codequery#79]
when run command 
"cmake -G "Unix Makefiles" -DBUILD_QT5=ON .. -Wno-dev"
it will shows 

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

and it needs to install another package 
$ sudo apt install qttools5-dev

Please update document , thanks.

**Comment by ruben2020** [comment]
@richliu Thank you. I will do so.

**Comment by ruben2020** [comment]
Updated in documentation
