### ISSUE TITLE
[Feature] Visual Studio Code extension

### ISSUE THREAD

**Issue by pidgeon777** [ruben2020/codequery#80]
It would be great to have an extension for Visual Studio Code for example making use of the codequery command line tool.

**Comment by ruben2020** [comment]
@pidgeon777  Currently, there is a plugin for vim, but not yet for other IDEs.

**Comment by ruben2020** [comment]
@pidgeon777 The first version of the Visual Studio Code extension for CodeQuery has been released. This is the Github page: [codequery4vscode](https://github.com/ruben2020/codequery4vscode). This is the Visual Studio Code Extension Marketplace page: [ruben2020.codequery4vscode](https://marketplace.visualstudio.com/items?itemName=ruben2020.codequery4vscode).

**Comment by pidgeon777** [comment]
Really cool. Great work!
