### ISSUE TITLE
[Feature] Highlight current function

### ISSUE THREAD

**Issue by LSergM** [ruben2020/codequery#82]
Hello everyone.
I would like to say thank you for this app I enjoy it a lot.

It will be great to have this feature.
Description:
When your cursor stay inside a function it will highlight current function from the list.
![image](https://user-images.githubusercontent.com/26021027/77463289-a926b700-6e05-11ea-89a2-4dc4154d8db3.png)

**Comment by ruben2020** [comment]
Thank you. That's a great idea.

**Comment by LSergM** [comment]
Hello Ruben.
I would like to ask you about opportunity to get bin files from "develop" branch.
Could you explain me how could I do it? I would like to test new functionality.
Thank you.

**Comment by ruben2020** [comment]
Hi @LSergM 
It's easier if you're using Linux or Mac.

Try this:
`git clone https://github.com/ruben2020/codequery`
`cd codequery`
`git checkout develop`

After this, follow the steps in the [INSTALL-LINUX.md](https://github.com/ruben2020/codequery/blob/develop/doc/INSTALL-LINUX.md) file.

**Comment by ruben2020** [comment]
@LSergM The feature you requested has been added to the develop branch.
