### ISSUE TITLE
Icon theme "elementary" not found.

### ISSUE THREAD

**Issue by LSergM** [ruben2020/codequery#83]
When I press the 
> Open button 

in Open CQ database file window then the CQ utility closes.
OS: Ubuntu 19.10 eoan
Kernel: x86_64 Linux 5.3.0-18-generic
LXDE
Branch develop

**Comment by ruben2020** [comment]
Is this Ubuntu 19.10 or Lubuntu 19.10? Is it LXDE or LXQt?

**Comment by LSergM** [comment]
This is Lubuntu 19.10.
I am not sure about second question but It looks like 
- Finding desktop environment...found as 'LXDE'

**Comment by LSergM** [comment]
I played around with different settings of Icons Theme and got following result

> codequery 
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/scalable/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"
osboxes@osboxes:/home/Share$ codequery 
osboxes@osboxes:/home/Share$ codequery 
osboxes@osboxes:/home/Share$ codequery 
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/scalable/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"
osboxes@osboxes:/home/Share$ codequery 
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/scalable/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"

**Comment by ruben2020** [comment]
Did you build for Qt5 or Qt4?

**Comment by LSergM** [comment]
I use Qt 5 to buid it.

**Comment by ruben2020** [comment]
To get rid of the error "Icon theme elementary not found", use this:
`sudo apt-get install elementary-icon-theme`

However, the closing of CodeQuery after fixing that, only happens with Lubuntu LXQt 19.10. It does not happen with Ubuntu 19.10. It also does not happen with Lubuntu LXDE 18.04. I use Arch Linux and it also does not happen on the latest Arch Linux.

So, I think this this is problem of Lubuntu 19.10 based on LXQt.

**Comment by ruben2020** [comment]
Using CodeQuery based on Qt4 does not have this problem on Lubuntu 19.10. Using CodeQuery based on Qt5 does not have this problem on Ubuntu 19.10. Would you consider switching to Ubuntu 19.10?

**Comment by LSergM** [comment]
After rebuilding CodeQuery by Qt4 I was able to open a db file. So this is great.
But than I have tried to use grep command and got segmentation fault

> Reading symbols from codequery...
(No debugging symbols found in codequery)
[New LWP 4350]
[New LWP 4353]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `codequery'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d02259515a in strrevcmp(QString, QString) ()
[Current thread is 1 (Thread 0x7f2776751640 (LWP 4350))]

**Comment by ruben2020** [comment]
Thanks. I just fixed the segmentation fault and committed to the develop branch. But there is still some problem with the function list on the bottom left when using grep. Still need to check that.

**Comment by ruben2020** [comment]
Good news @LSergM - I have fixed the function list bug for grep. Now updated to the develop branch. I guess we can soon approach release of a new version. Please do try it out and let me know if you're satisfied with it. Thank you very much for your support.

**Comment by LSergM** [comment]
@ruben2020 I have tested the new update and it looks great. Thank you for your work and help.
