### ISSUE TITLE
Unsupported cscope parameters: -c is required. -q, -b and -R are optional. The rest should not be used.

### ISSUE THREAD

**Issue by d4em0n** [ruben2020/codequery#88]
Hi, i try to run cqmakedb on c project but i got the following error.
```
> cqmakedb -s cq.db -c cscope.out -t tags -p
cscope.out sanity check Error
Unsupported cscope parameters: -c is required. -q, -b and -R are optional. The rest should not be used.
```

**Comment by ruben2020** [comment]
@d4em0n Did you first create a `cscope.files` file then run cscope like this:
`cscope -cb`
You can find this info in the [HOWTO-LINUX](https://github.com/ruben2020/codequery/blob/master/doc/HOWTO-LINUX.md) and [HOWTO-WINDOWS](https://github.com/ruben2020/codequery/blob/master/windows-install/wincommon/HOWTO-WINDOWS.txt) files.

**Comment by dariomx** [comment]
Greetings Ruben. Using -c option seems to considerably slow down the indexing of cscope; not sure why though. Is there any reason for not using the compressed format? (aka, without -c option).

I also wonder if the inverted index variant would be useful for codequery as well (-q option)

Thanks.

**Comment by ruben2020** [comment]
@dariomx `-c` is used because cqmakedb does not parse the binary non-compressed version of cscope.out at the moment. But this could be a suggestion of improvement if that really makes a difference in indexing speed.

**Comment by ruben2020** [comment]
@brent-casavant-hpe I think I'll start looking into this again soon. It sounds like a good feature to add to cqmakedb.

**Comment by ruben2020** [comment]
@brent-casavant-hpe @pidgeon777 @dariomx @d4em0n I have added the ability to support compressed cscope.out files, but it's currently experimental. It's on the `develop` branch.

**Comment by ruben2020** [comment]
@brent-casavant-hpe @pidgeon777 @dariomx @d4em0n Support for compressed cscope.out supported experimentally in v0.27.0. This issue can now be closed.
