### ISSUE TITLE
On macbook, window width is too wide and cannot be resized

### ISSUE THREAD

**Issue by girishji** [ruben2020/codequery#96]
It automatically keeps widening window so that a chunk of window is not visible in the viewport. The box that shows path to file  is not readable since it is cut off. If I resize the window to fit the screen, a few moments later (after a few searches) the window is too wide again.
Also, please rearrange the boxes so that path to file is on the left half of screen, and buttons can be in 2 rows.
Using v0.25.0

**Comment by ruben2020** [comment]
@girishji Is it possible for you to provide a screenshot? Thanks.

**Comment by girishji** [comment]
It happens when the file whose contents appear in the right hand bottom window has a long path that exceeds the box width where path is seen.

<img width="1436" alt="Screen Shot 2022-12-14 at 9 18 41 AM" src="https://user-images.githubusercontent.com/16529248/207542719-82496c40-0bbb-4a1e-9496-59da745915d8.png">

**Comment by girishji** [comment]
See how window automatically resized to spill past the viewport on the right side, when I selected keymap.c file in the top window

**Comment by girishji** [comment]
Also, opening file using external editor does not work on Mac. Maybe there is a way to use applescript to launch gvim (for instance), a la 'gedit %f ...' for linux.

**Comment by ruben2020** [comment]
@girishji As for the external editor, I could add this way on Windows and Linux (see below). How come there's no top menu bar in MacOS?

Please see images below:

![image](https://user-images.githubusercontent.com/2457121/208073026-ba429847-fcad-4a31-bbe6-e47e14f198af.png)
![image](https://user-images.githubusercontent.com/2457121/208073268-f0d9ec75-ef06-440d-9ff2-9a304368c825.png)

**Comment by girishji** [comment]
Ruben, 
- There is a top menu bar in MacOS, it is just not included in my screenshot
- Please use the string for default "open -t %f" (I tested this)
(-t  opens in the default editor, 'open -a TextEdit %f' will open file with textedit for example, etc)
I am not sure how to specify line number.

**Comment by ruben2020** [comment]
@girishji Thanks! I have fixed the GUI bug and also used "open -t %f" (as default on Mac, if a config file was not yet created or not found) and it's currently on the `develop` branch, but it's not yet released. If you can build it yourself, then you can try it out. Otherwise, you need to wait for me to release it officially. It may take a few days to appear on Brew.

**Comment by girishji** [comment]
Thank you!

**Comment by ruben2020** [comment]
@girishji Fixed in version 0.26.0. It should appear in Brew within two days.
